services:
  # FastAPI service
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/students_db
    networks:
      - app-network

  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allow empty password (not recommended for production)
      MYSQL_DATABASE: students_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
