services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - redis
    environment:
      - FLASK_APP=app/views.py
      - FLASK_ENV=development
  worker:
    build: .
    depends_on:
      - rabbitmq
      - redis
    restart: always
    entrypoint: [ "celery", "-A", "app.tasks", "worker", "--loglevel=info" ]
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  redis:
    image: "redis:6.0"
    volumes:
      - ./redis-data:/data  # Mount host directory to Redis data directory
